---
kind: pipeline
type: docker
name: arm-master

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache
  - name: build-master
    image: plugins/docker
    settings:
      repo: embeddedreality/arm-toolchain
      use_cache: true
      username:
        from_secret: repo_username
      password:
        from_secret: repo_password
    volumes:
      - name: docker
        path: /var/lib/docker

trigger:
  branch:
    - master

volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/${DRONE_REPO}/docker
      
