set(PACKAGE_VENDOR Embeddedreality CACHE STRING "")

set(CMAKE_BUILD_TYPE MinSizeRel CACHE STRING "")
set(LLVM_INCLUDE_DOCS OFF CACHE BOOL "")
set(LLVM_INCLUDE_EXAMPLES OFF CACHE BOOL "")
set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "")
set(LLVM_INCLUDE_BENCHMARKS OFF CACHE BOOL "")

set(LLVM_TARGETS_TO_BUILD X86;ARM;AArch64;AVR;RISCV CACHE STRING "")
set(LLVM_ENABLE_PROJECTS "clang;clang-tools-extra;lld;lldb;llvm" CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES "compiler-rt;libunwind;libcxxabi;libcxx" CACHE STRING "")
set(LLVM_LINK_LLVM_DYLIB ON CACHE BOOL "")
set(LLVM_ENABLE_PIC ON CACHE BOOL "")
set(LLVM_ENABLE_RTTI ON CACHE BOOL "")
set(LLVM_ENABLE_EH ON CACHE BOOL "")
set(LLVM_ENABLE_LIBCXX ON CACHE BOOL "")
set(LLVM_ENABLE_PER_TARGET_RUNTIME_DIR ON CACHE BOOL "")
set(LLVM_USE_RELATIVE_PATHS_IN_FILES ON CACHE BOOL "")
if(NOT APPLE)
  set(LLVM_ENABLE_LLD ON CACHE BOOL "")
endif()
set(LLVM_ENABLE_LTO ON CACHE BOOL "")
set(ENABLE_LINKER_BUILD_ID ON CACHE BOOL "")

set(CLANG_DEFAULT_RTLIB compiler-rt CACHE STRING "")
set(CLANG_DFEAULT_CXX_STDLIB libc++ CACHE STRING "")
if(NOT APPLE)
  set(CLANG_DEFAULT_LINKER lld CACHE STRING "")
  set(CLANG_DEFAULT_OBJCOPY llvm-objcopy CACHE STRING "")
endif()
set(CLANG_CONFIG_FILE_SYSTEM_DIR ${CMAKE_INSTALL_PREFIX}/etc)

list(APPEND BUILTIN_TARGETS "default")
list(APPEND RUNTIME_TARGETS "default")

if(APPLE)
  set(LLDB_USE_SYSTEM_DEBUGSERVER ON CACHE BOOL "")
  set(COMPILER_RT_ENABLE_TVOS OFF CACHE BOOL "")
  set(COMPILER_RT_ENABLE_WATCHOS OFF CACHE BOOL "")
else()
  set(LIBCXX_HAS_MUSL_LIBC ON CACHE BOOL "")
  set(COMPILER_RT_BUILD_LIBFUZZER OFF CACHE BOOL "")
  set(COMPILER_RT_BUILD_SANITIZERS OFF CACHE BOOL "")
  set(COMPILER_RT_BUILD_XRAY OFF CACHE BOOL "")
  set(COMPILER_RT_BUILD_PROFILE OFF CACHE BOOL "")
endif()

set(COMPILER_RT_USE_BUILTINS_LIBRARY ON CACHE BOOL "")
set(LIBUNWIND_ENABLE_SHARED OFF CACHE BOOL "")
set(LIBUNWIND_INSTALL_LIBRARY OFF CACHE BOOL "")
set(LIBUNWIND_USE_COMPILER_RT ON CACHE BOOL "")
set(LIBCXXABI_ENABLE_SHARED OFF CACHE BOOL "")
set(LIBCXXABI_ENABLE_STATIC_UNWINDER ON CACHE BOOL "")
set(LIBCXXABI_INSTALL_LIBRARY OFF CACHE BOOL "")
set(LIBCXXABI_USE_COMPILER_RT ON CACHE BOOL "")
set(LIBCXXABI_USE_LLVM_UNWINDER ON CACHE BOOL "")
set(LIBCXX_USE_COMPILER_RT ON CACHE BOOL "")
set(LIBCXX_ENABLE_SHARED OFF CACHE BOOL "")
set(LIBCXX_ENABLE_STATIC_ABI_LIBRARY ON CACHE BOOL "")
set(LIBCXX_ABI_VERSION 2 CACHE STRING "")


set(LLVM_BUILTIN_TARGETS "${BUILTIN_TARGETS}" CACHE STRING "")
set(LLVM_RUNTIME_TARGETS "${RUNTIME_TARGETS}" CACHE STRING "")

set(LLVM_TOOLCHAIN_TOOLS
  dsymutil
  llc
  llvm-addr2line
  llvm-ar
  llvm-as
  llvm-config
  llvm-cov
  llvm-cxxfilt
  llvm-dwarfdump
  llvm-dwp
  llvm-lib
  llvm-nm
  llvm-objcopy
  llvm-objdump
  llvm-profdata
  llvm-ranlib
  llvm-readelf
  llvm-readobj
  llvm-size
  llvm-strings
  llvm-strip
  llvm-symbolizer
  opt
  sancov
  cmake-exports
  CACHE STRING "")

set(LLVM_DISTRIBUTION_COMPONENTS
  builtins
  runtimes
  LTO
  LLVM
  lld
  clang-resource-headers
  clang-cpp
  clang
  clangd
  ${LLVM_TOOLCHAIN_TOOLS}
  CACHE STRING "")
